import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";

import MouseGradient from '@/components/MouseGradient';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: 'Coincooker Portfolio',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} px-5 container mx-auto bg-gray-900 text-white antialiased`}
      >
          <MouseGradient />
          {children}
      </body>
    </html>
  );
}
